spring:
  application:
    name: task_backend
  datasource:
    username: ${PGSQL_USER}
    password: ${PGSQL_PASSWORD}
    url: jdbc:postgresql://localhost:5432/${PGSQL_DB_NAME}
    driver: org.hibernate.dialect.PostgreSQL10Dialect
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8761
  servlet:
    context-path: /task
token:
  secret:
    key: Hlm0K114HtPEUWHzZ6Kv4xTAwe2WCg7X
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855